.PHONY: clean All

All:
	@echo "----------Building project:[ latino - Debug ]----------"
	@$(MAKE) -f  "latino.mk" PreBuild && $(MAKE) -f  "latino.mk"
clean:
	@echo "----------Cleaning project:[ latino - Debug ]----------"
	@$(MAKE) -f  "latino.mk" clean
