.TH Latino manual
.SH Funciones
.B Funcion
.PP
.br
En Latino podemos crear funciones incluyendo parametros de una manera basica o avanzada.
Pondremos como ejemplo lo siguiente:
  funcion nombre(parametro)
    retorno parametro
  fin
  escribir(nombre("hola")
Así retornando lo que se incluya en el parametro
