# Watcom Makefile for PDCurses - DOS
#
# Usage: wmake -f [path\]Makefile.wcc [DEBUG=Y] [MODEL=c|h|l|m|s|f] [target]
#
# where target can be any of:
# [all|demos|pdcurses.lib|testcurs.exe...]

!ifndef MODEL
MODEL = l
!endif

!ifdef %PDCURSES_SRCDIR
PDCURSES_SRCDIR = $(%PDCURSES_SRCDIR)
!else
PDCURSES_SRCDIR = ..
!endif

osdir = dos

TARGET = dos

!ifeq MODEL f
LTARGET	= dos4g
!else
LTARGET	= dos
!endif

CFLAGS =

!include $(PDCURSES_SRCDIR)/common/watcom.mif
