.PHONY: clean All

All:
	@echo "----------Building project:[ src - Debug ]----------"
	@"$(MAKE)" -f  "src.mk"
clean:
	@echo "----------Cleaning project:[ src - Debug ]----------"
	@"$(MAKE)" -f  "src.mk" clean
